config/routes.rb
EbaySniper::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "users", :sessions => "sessions" }
  
  resources :search do
    member do
      post :new
    end
  end
  
  resources :auctions do
    collection do
      post :remove_multiple
      post :restore_multiple
      post :create_multiple
      get :import
    end
    member do
      post :restore
      get :update_info
    end
  end

  resources :users
  resources :home
  resources :notifications
  
  get "call_handler", :to => "notifications#receive"
  
  devise_scope :user do
    get "user_root", :to => "users#check_token"
    get "user/add_token", :to => "users#add_token"
    get "user/check_token", :to => "users#check_token"
    get "user/consent_failed", :to => "users#consent_failed"
  end

  root :to => "home#index"

  

end

app/models/search.rb
class Search

  def get_results(search, current_user)
    search = search.to_s.downcase.split(" ")
    unless search == ""
      auctions = Auction.select { |a| a.user_id == current_user.id && search.any? { |word|
        a.item[:get_item_response][:item][:title].to_s.downcase.include?(word) ||
        a.item[:get_item_response][:item][:description].to_s.downcase.include?(word) ||
        a.item[:get_item_response][:item][:selling_status][:converted_current_price].to_s.downcase.include?(word) ||
        a.max_bid.to_s.downcase.include?(word) ||
        a.item_id.to_s.downcase.include?(word)
      } }
      auctions.uniq!
      auctions = auctions.sort_by { |a| [a.item[:get_item_response][:item][:title]] }
    end
    auctions ||= []
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @auctions = Search.new.get_results(params[:search], current_user)
    
    respond_to do |format|
      format.html
    end
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_results.html.erb
<table class="table table-striped">
  <thead>
    <tr>
	  <th width="10%">Picture</th>
      <th width="60%">Item</th>
	  <th width="8%">Time Left</th>
	  <th>Current price</th>
      <th>Max bid</th>
    </tr>
  </thead>

  <tbody>
    <% @auctions.each do |auction| %>
	  <tr onclick="location.href='<%= edit_auction_path(auction) %>'" class="auction-link">
		<td style="vertical-align: middle; text-align: center;"><%= image_tag auction.picture[0], :maxsize => "100x100" %></td>
		<td>
		<h3><%= truncate(auction.item[:get_item_response][:item][:title], :length => 60) %></h3>
		<%= truncate(strip_tags(auction.item[:get_item_response][:item][:description]),
								:length => 300, :separator => ' ') %>
		</td>
		<td><%= get_time_remaining auction %></td>
		<td><%= number_to_currency auction.item[:get_item_response][:item][:selling_status][:converted_current_price] %></td>
		<td><%= number_to_currency auction.max_bid %></td>
	  </tr>
	<% end %>
  </tbody>
</table>

app/views/search/index.html.erb
<legend>Search Results</legend>
<br/>

<div id="results">
  <% if @auctions != [] %>
    <%= render :partial => "results" %>
  <% else %>
	<div class="alert alert-error">
	  <strong>Sorry!</strong> Your search returned no results. Try using less words and then work your way up to more specific search terms.
	  <br/><br/>
	  You can search through your added auctions by title, description, item ID, current price, and max bid.
	</div>
  <% end %>
</div>

app/views/search/new.html.erb
<legend>Search Results</legend>
<br/>

<div id="results">
  <% if @auctions != [] %>
    <%= render :partial => "results" %>
  <% else %>
	<div class="alert alert-error">
	  <strong>Sorry!</strong> Your search returned no results. Try using less words and then work your way up to more specific search terms.
	  <br/><br/>
	  You can search through your added auctions by title, description, item ID, current price, and max bid.
	</div>
  <% end %>
</div>