config/routes.rb
EbaySniper::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "users", :sessions => "sessions" }
  
  resources :search do
    member do
      post :new
    end
  end
  
  resources :auctions do
    collection do
      post :remove_multiple
      post :restore_multiple
      post :create_multiple
      get :import
    end
    member do
      post :restore
      get :update_info
    end
  end

  resources :users
  resources :home
  resources :notifications
  
  get "call_handler", :to => "notifications#receive"
  
  devise_scope :user do
    get "user_root", :to => "users#check_token"
    get "user/add_token", :to => "users#add_token"
    get "user/check_token", :to => "users#check_token"
    get "user/consent_failed", :to => "users#consent_failed"
  end

  root :to => "home#index"

  

end

app/models/user.rb
require 'devise/strategies/base'
require 'devise'

module Devise
  module Strategies
    # Remember the user through the remember token. This strategy is responsible
    # to verify whether there is a cookie with the remember token, and to
    # recreate the user from this cookie if it exists. Must be called *before*
    # authenticatable.
    class EbayAuthenticatable < Authenticatable

      def valid?
        if params and params.is_a?(Hash) and params[:user] and params[:user].is_a?(Hash) and params[:user][:email] and not (params[:user][:email].to_s =~ /@/)
          params_authenticatable? && valid_params_request? &&
            valid_params? && with_authentication_hash(:params_auth, params_auth_hash)
          return true
        else
          return false
        end
      end

      # To authenticate a user we deserialize the cookie and attempt finding
      # the record in the database. If the attempt fails, we pass to another
      # strategy handle the authentication.
      def authenticate!
        resource = mapping.to.where(:username => authentication_hash[:email]).first if authentication_hash
        resource ||= mapping.to.new if resource.nil?

        username = authenticate_against_ebay(authentication_hash[:email], password)

        if username
          resource.username = username
          resource.password = password
          resource.password_confirmation = password
          resource.save if resource.changed?
        end

        return fail(:invalid) unless username and resource

        if validate(resource) { not resource.nil? }
          success!(resource)
        end
      end

      def authenticate_against_ebay(username, password)
        m = Mechanize.new
        lp = m.get "https://signin.sandbox.ebay.com/ws/eBayISAPI.dll?SignIn"
        f = lp.form_with(:name => "SignInForm")
        f.field_with(:name => "userid").value = username
        f.field_with(:name => "pass").value = password
        np = f.submit

        if np.body =~ /password is incorrect/
          return false
        end

        myebay = m.get "http://my.sandbox.ebay.com/ws/eBayISAPI.dll?MyeBay"
        return myebay.search("[class='mbg-nw']").text
      end

      private

      def decorate(resource)
        super
        # resource.extend_remember_period = mapping.to.extend_remember_period if resource.respond_to?(:extend_remember_period=)
      end

    end
  end
end

module Devise
  module Models
    module EbayAuthenticatable
      def self.included(base)
        base.extend ClassMethods
      end

      module ClassMethods
      end
    end


    module Validatable
      # All validations used by this module.
      # VALIDATIONS = [ :validates_presence_of, :validates_uniqueness_of, :validates_format_of,
      # :validates_confirmation_of, :validates_length_of ].freeze

      def self.included(base)
        base.extend ClassMethods
        assert_validations_api!(base)

        base.class_eval do
          validates_presence_of   :email, :if => :email_required?
          validates_uniqueness_of :email, :case_sensitive => (case_insensitive_keys != false), :allow_blank => false, :if => :email_changed?
          validates_format_of     :email, :with => email_regexp, :allow_blank => false, :if => :email_changed?

          validates_presence_of     :password, :if => :password_required?
          validates_confirmation_of :password, :if => :password_required?
          validates_length_of       :password, :within => password_length, :allow_blank => true
        end
      end
    end
  end
end

Warden::Strategies.add(:ebay_authenticatable, Devise::Strategies::EbayAuthenticatable)
Devise.add_module(:ebay_authenticatable,
                  :strategy => true,
                  :model => "app/models/user.rb")

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :ebay_authenticatable

  has_many :auctions, dependent: :destroy
  validates :phone_number, :allow_blank => true, :length => { :is => 12 }, :format => { :with => /\A[+]\d+\z/,
                                                                                        :message => "should include your country code. A US number would be +1##########." }
  validates_uniqueness_of :phone_number, :allow_blank => true, :message => "is already tied to an account."
  before_create do
    self.auth_token ||= SecureRandom.hex(23)
  end

  def self.currently_online
    online_ids = $redis.keys("ebay_sniper:online_users:*").map { |v| v.gsub("ebay_sniper:online_users:", "") }
    User.where(:id => online_ids)
  end

  def consent_failed?
    if self.auth_token_exp < Time.now
      return true
    else
      return false
    end
  end

  def online?
    if self.id
      return $redis.get("ebay_sniper:online_users:#{self.id}") == "1"
    end
    return false
  end

  def email_required?
    return false
  end
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
  before_filter :authenticate_user!

  # GET /auctions
  # GET /auctions.json
  def index
    if params[:status] != nil
      current_user.update_attributes :preferred_status => params[:status]
    end
    if params[:sort] != nil
      current_user.update_attributes :preferred_sort => params[:sort]
    end
    @auctions = Auction.sort_auctions(current_user)

    respond_to do |format|
      format.html
      format.json { render json: @auctions }
      format.js { render :layout => false }
    end
  end

  # GET /auctions/new
  # GET /auctions/new.json
  def new
    @auction = Auction.new

    respond_to do |format|
      format.html
      format.json { render json: @auction }
    end
  end

  # GET /auctions/1/edit
  def edit
    @auction = Auction.find(params[:id])
    @picture_id = params[:pic].to_i

    respond_to do |format|
      format.html
      format.js { render :layout => false }
    end
  end

  # POST /auctions
  # POST /auctions.json
  def create
    @auction = Auction.new(params[:auction])
    @auction.user = self.current_user

    respond_to do |format|
      if @auction.save
        # Needs to be enqueued after save so auction has ID
        @auction.enqueue_job
        format.html { redirect_to edit_auction_path(@auction.id), notice: 'Auction was successfully created.' }
        format.js
        format.json { render json: @auction, status: :created, location: @auction }
      else
        format.html { render action: 'new' }
        format.js
        format.json { render json: @auction.errors.full_messages }
      end
    end
  end

  # PUT /auctions/1
  # PUT /auctions/1.json
  def update
    @auction = Auction.find(params[:id])

    respond_to do |format|
      if @auction.update_attributes(params[:auction])
        format.html { redirect_to edit_auction_path, notice: 'Auction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @auction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /auctions/1
  # DELETE /auctions/1.json
  def destroy
    @auction = Auction.find(params[:id])
    @auction.remove_auction

    respond_to do |format|
      format.html { redirect_to auctions_url }
      format.json { head :no_content }
    end
  end

  # Restores a deleted auction
  def restore
    @auction = Auction.find(params[:id])
    @auction.restore_auction

    redirect_to edit_auction_path, notice: 'Auction was successfully restored.'
  end

  def remove_multiple
    Auction.remove_multiple params[:auction_ids]
    @auctions = Auction.find(params[:auction_ids])
    
    respond_to do |format|
      format.js
    end
  end
  
  def restore_multiple
    Auction.restore_multiple params[:auction_ids]
    @auctions = Auction.find(params[:auction_ids])

    respond_to do |format|
      format.js
    end
  end

  # POST /auctions
  # POST /auctions.json
  def create_multiple
    # Get the checked auctions
    @auctions = Auction.prepare_multiple params[:auction], current_user

    # If there are errors, re-render the page and show the auctions with errors. Else, show auctions#index.
    if @auctions.detect { |a| not a.errors.empty? }
      respond_to do |format|
        format.html { render 'import' }
      end
    else
      respond_to do |format|
        format.html { redirect_to auctions_path }
      end
    end
  end

  def import
    @auctions = EbayAction.new(current_user).import

    respond_to do |format|
      format.html
    end
  end

  def update_info
    @auction = Auction.find(params[:id])
    @auction.update_auction

    redirect_to edit_auction_path
  end
end

app/helpers/auctions_helper.rb
module AuctionsHelper

  def get_time_remaining(auction)
    # Find the time remaining in seconds
    time_left = (Time.parse(auction.item[:get_item_response][:item][:listing_details][:end_time]).localtime - Time.now).to_i
    if time_left < 0
      return "0 seconds"
    end
    # Format the time
    mins = time_left / 60
    hours = mins / 60
    days = hours / 24
    
    if days > 0
      "#{days}d #{hours % 24}h"
    elsif hours > 0
      "#{hours}h #{mins % 60}m"
    elsif mins > 0
      "#{mins}m #{time_left % 60}s"
    else
      "#{time_left} seconds"
    end
  end
  
  def check_selected(sort)
    if current_user.preferred_sort == sort.to_s
      return "selected='selected'"
    else
      return "false"
    end
  end

  def format_price(converted_price)
    # Have to be explicit because number_to_currency helper isn't included.
    return ActionController::Base.helpers.number_to_currency converted_price
  end
end

app/views/auctions/_auction.html.erb
<div class="pull-right"><%= link_to 'Refresh Auction', update_info_auction_path, :class => "btn btn-success" %></div>
<h1 align="center">Listing Details</h1>
<br/>
<br/>
<div class="row-fluid">
  <div class="span4" align="center">
	<div class="canvas">
	  <%= render :partial => "ebay_pic" %>
	</div>
	<br/>
	<ul class="thumbnails">
	  <% @auction.picture.each_with_index do |pic, index| %>
	    <li class="span3">
	      <%= link_to image_tag(pic), edit_auction_path(:pic => index), :class => "thumbnail", :remote => true %>
	    </li>
	  <% end %>
	</ul>
	<br/>
	<br/>
	<div align="left">
	  Item number: <%= @auction.item_id %>
	  <br/>
	  Auction status: <%= @auction.auction_status %>
	</div>
  </div>

  <div class="span8">
	<h1><u><%= link_to @auction.item[:get_item_response][:item][:title], @auction.item[:get_item_response][:item][:listing_details][:view_item_url], :target => '_blank' %></u></h1>
	<br/>
	<%= sanitize(@auction.item[:get_item_response][:item][:description])%>
	<br/>
	<br/>
	
	<table class="table">
      <thead>
        <tr>
	      <th>Current Price</th>
          <th>Time Left</th>
	      <th>Seller</th>
	      <th>Bid Count</th>
		  <% if @auction.item[:get_item_response][:item][:listing_details][:has_reserve_price] == "true" %>
			<th>Reserve Price</th>
		  <% end %>
        </tr>
      </thead>

      <tbody>
	      <tr>
			<td><%= number_to_currency @auction.item[:get_item_response][:item][:selling_status][:converted_current_price] %></td>
		    <td><%= get_time_remaining @auction %></td>
		    <% seller_user_id = @auction.item[:get_item_response][:item][:seller][:user_id] %>
		    <td><%= link_to seller_user_id, "http://feedback.sandbox.ebay.com/ws/eBayISAPI.dll?ViewFeedback2&userid=" +
			  seller_user_id + "&ftab=AllFeedback&items=25", :target => :_blank %></td>
		    <td><%= @auction.item[:get_item_response][:item][:selling_status][:bid_count] %></td>
			<% if @auction.item[:get_item_response][:item][:listing_details][:has_reserve_price] == "true" %>
			  <td><% @auction.item[:get_item_response][:item][:listing_details][:converted_reserve_price] %></td>
			<% end %>
	      </tr>
      </tbody>
    </table>

  </div>
</div>

app/views/auctions/_auction_index.html.erb
<div class="row-fluid">
<div class="span12">  
<ul class="nav nav-pills">
  <li class="<%= 'active' if current_user.preferred_status == 'All' %>"><%= link_to 'All',
	auctions_path(:status => "All"), :method => :get, :remote => true %></li>
  <li class="<%= 'active' if current_user.preferred_status == 'Active' %>"><%= link_to 'Active',
	auctions_path(:status => "Active"), :method => :get, :remote => true %></li>
  <li class="<%= 'active' if current_user.preferred_status == 'Won' %>"><%= link_to 'Won',
	auctions_path(:status => "Won"), :method => :get, :remote => true %></li>
  <li class="<%= 'active' if current_user.preferred_status == 'Lost' %>"><%= link_to 'Lost',
	auctions_path(:status => "Lost"), :method => :get, :remote => true %></li>
  <li class="<%= 'active' if current_user.preferred_status == 'Ended' %>"><%= link_to 'Ended',
	auctions_path(:status => "Ended"), :method => :get, :remote => true %></li>
  <li class="<%= 'active' if current_user.preferred_status == 'Deleted' %>"><%= link_to 'Deleted',
	auctions_path(:status => "Deleted"), :method => :get, :remote => true %></li>
  <li class="pull-right">
    <%= form_tag(auctions_path, :method => :get, :remote => true) do |f| %>
      Sort by:
	  <%= select_tag :sort, "<option value='time_asc'>Time: sooner-later</option>
	    <option value='time_desc' #{ check_selected 'time_desc' }>Time: later-sooner</option>
	    <option value='title_asc' #{ check_selected 'title_asc' }>Title: A-Z</option>
	    <option value='title_desc' #{ check_selected 'title_desc' }>Title: Z-A</option>
	    <option value='price_asc' #{ check_selected 'price_asc' }>Current Price: low-high</option>
	    <option value='price_desc' #{ check_selected 'price_desc' }>Current Price: high-low</option>
	    <option value='max_bid_asc' #{ check_selected 'max_bid_asc' }>Max Bid: low-high</option>
	    <option value='max_bid_desc' #{ check_selected 'max_bid_desc' }>Max Bid: high-low</option>".html_safe,
	    :onchange => "$(this.form).submit();",
	    :method => :get %>
	<% end %>
  </li>
</ul>
</div>
</div>

<% if current_user.preferred_status != "Deleted" %>
  <% path = remove_multiple_auctions_path %>
  <% button_title = "Delete Checked Auctions" %>
<% else %>
  <% path = restore_multiple_auctions_path %>
  <% button_title = "Restore Checked Auctions" %>
<% end %>

<%= form_tag path, :method => :post, :data => { :confirm => "Are you sure you want to #{button_title.split(' ')[0].downcase} your checked auctions?", :remote => true } do %>

  <% if @auctions != [] %>
    <table class="table table-striped">
      <thead>
        <tr>
	      <th width="10%">Picture</th>
          <th width="50%">Item</th>
	      <th width="9%">Time Left</th>
	      <th width="9%">Price</th>
          <th width="9%">Max bid</th>
	      <% if current_user.preferred_status != "Deleted" %>
	        <th width="3%" class="check-all">Delete</th>
	      <% else %>
	        <th width="3%" class="check-all">Restore</th>
	      <% end %>
        </tr>
      </thead>

      <tbody>
        <% @auctions.each do |auction| %>
	      <tr id="auction-<%= auction.id %>">
            <td class="auction-link" onclick="location.href='<%= edit_auction_path(auction) %>'" style="vertical-align: middle; text-align: center;" >
			  <%= image_tag auction.picture[0] %></td>
		    <td class="auction-link" onclick="location.href='<%= edit_auction_path(auction) %>'">
		    <h3><%= truncate(auction.item[:get_item_response][:item][:title], :length => 55) %></h3>
		    <%= truncate(strip_tags(auction.item[:get_item_response][:item][:description]), :length => 300, :separator => ' ') %>
		    </td>
		    <td class="auction-link" onclick="location.href='<%= edit_auction_path(auction) %>'"><%= get_time_remaining auction %></td>
		    <td class="auction-link" onclick="location.href='<%= edit_auction_path(auction) %>'"><%= number_to_currency auction.item[:get_item_response][:item][:selling_status][:converted_current_price] %></td>
		    <td class="auction-link" onclick="location.href='<%= edit_auction_path(auction) %>'"><%= number_to_currency auction.max_bid %></td>
		    <td class="delete_auction" style="text-align: center;" auction-id="<%= auction.id %>"><%= check_box_tag 'auction_ids[]', auction.id, false %></td>
	      </tr>
	    <% end %>
      </tbody>
    </table>
    <br/>
  <% end %>

  <a data-toggle="modal" href="#new_auction" class="btn btn-primary">Add Auction</a> |
  <button type="submit" class="btn btn-danger" data-remote="true"><%= button_title %></button>

  <script>
    $('.check-all').click(function(event) {
      // If the amount of checked checkboxes does not equal the amount of checkboxes, then check all of them. Otherwise, uncheck all.
      if ($('[type="checkbox"]').length != $('input:checked').length) {
        $('[type="checkbox"]').prop('checked', true);
      }
      else {
        $('[type="checkbox"]').prop('checked', false);
      }
    });
  </script>

<% end %>

app/views/auctions/_ebay_pic.html.erb
<%= image_tag @auction.picture[@picture_id], :id => 'ebay-pic' %>

app/views/auctions/_errors.html.erb
<% if auction.errors.empty? %>
  <div id="auction-update-result" class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>Well done!</strong> Your account was successfully updated.
  </div>
<% else %>
  <div id="auction-update-result" class="alert alert-error alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>

    <h4><%= pluralize(auction.errors.count, "error") %> prohibited this auction from being saved:</h4>
    <ul style="padding-top: 10px">
      <% auction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/auctions/_new_modal.html.erb
  <div id="new_auction" class="modal hide fade in">
    <div>
	  <a class="close" data-dismiss="modal">×</a>
    </div>
	<% auction = Auction.new %>
  	<%= form_for auction, { :remote => true } do |f| %>
	  <% if not auction.errors.any? %>
		<br/>
	  <% end %>
	  <div class="modal-body">
		<legend>New Auction</legend>
		<br/>
		<div class="control-group">
	  	  <label class="control-label" for="item_id">eBay URL or item number</label>
	  	  <div class="controls">
	  		<%= f.text_field :item_id, :id => "testing" %>
	  	  </div>
		</div>
	    <br/>
	    <div class="control-group">
	      <label class="control-label" for="max_bid">Max bid</label>
	      <div class="controls">
	  	    <%= f.text_field :max_bid %>
	      </div>
	    </div>
	    <br/>
	    <div class="control-group">
	      <label class="control-label" for="lead_time">Lead time (in seconds from 0 to 3)</label>
	      <div class="controls">
	  	    <%= f.text_field :lead_time %>
	      </div>
	    </div>
	    <br/>
	    <div class="control-group">
	      <label class="control-label" for="select01">
			How would you like to be notified about <br/>critical auction updates (ex: being outbid)?
		  </label>
	      <div class="controls">
		    <%= f.select :user_notification, ["Do not notify", "Call", "Text Message"] %>
	      </div>
	    </div>
      </div>
      <div class="modal-footer" style="text-align: left;">
	    <button type="submit" class="btn btn-primary" data-loading-text="Creating...">Create Auction</button> |
		<%= link_to 'Import Auctions', import_auctions_path, :method => :get, :class => "btn btn-success" %></li> |
        <a href="#" class="btn" data-dismiss="modal">Close</a>
      </div>
	<% end %>
  </div>

app/views/auctions/_snipe.html.erb
<%= form_for(@auction) do |f| %>
  <% if @auction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@auction.errors.count, "error") %> prohibited this auction from being saved:</h2>

      <ul>
      <% @auction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>	
	<br/>
	<br/>
  <% end %>

  <div class="row">
    <div class="span12">	
	  <h1>Snipe Options</h1>
	  <br/>
	  <br/>
	  <div class="control-group">  
	    <label class="control-label" for="max_bid">Max bid</label>  
	    <div class="controls">  
	  	  <%= f.text_field :max_bid %>
	    </div> 
	  </div>
	  <br/>
	  <div class="control-group">  
	    <label class="control-label" for="lead_time">Lead time (in seconds from 0 to 3)</label>  
	    <div class="controls">  
	  	  <%= f.text_field :lead_time %>
	    </div> 
	  </div>
	  <br/>
	  <div class="control-group">  
	    <label class="control-label" for="select01">How would you like to be notified about critical auction updates (ex: being outbid)?</label>  
	    <div class="controls">  
		  <%= f.select :user_notification, ["Do not notify", "Call", "Text Message"] %>
	    </div>  
	  </div>
	  <br/>
	  <button type="submit" class="btn btn-primary">Save Changes</button> |
	
	  <% if @auction.auction_status != "Deleted" %>
	  	<%= link_to 'Remove Auction', @auction, :method => :delete, :data => {
			confirm: 'Are you sure you want to restore this auction?' }, :class => "btn btn-danger" %> |
	  <% else %>
		<%= link_to 'Restore Auction', restore_auction_path(:id => @auction.id), :method => :post, :data => {
			confirm: 'Are you sure you want to restore this auction?' }, :class => "btn" %> |
	  <% end %>
	
	  <%= link_to 'Back', auctions_path, :class => "btn" %>
    </div>
  </div>	
<% end %>

app/views/auctions/create.js.erb
<% if @auction.errors.empty? %>
  $('#new_auction').modal('hide');
  $('#new_auction').detach();
  window.location.replace("<%= escape_javascript(edit_auction_path(@auction.id)); %>");
<% else %>
  $('#auction-update-result').detach();
  $('#new_auction .modal-body legend').before('<%= escape_javascript(render('auctions/errors', :auction => @auction)) %>');
  $('#new_auction, .modal-body').animate({scrollTop:0}, 'fast');
  $('#auction-update-result').effect("highlight", {}, 1000);
<% end %>

app/views/auctions/edit.html.erb
<%= render :partial => "auction" %>

<br/>
<br/>
<hr color="#0066FF" size="3">
<br/>
<br/>

<%= render "snipe" %>

app/views/auctions/edit.js.erb
// $(document).ready(function() {
//   $('#ebay-pic').css('marginTop', $('#ebay-pic').parent().height() / 2 - $('#ebay-pic').height() / 2);
// });


// When a thumbnail is clicked, the current ebay-pic is animated to disappear by shrinking in from its center, and the thumbnail's ebay-pic is animated from
// Being 0x0 in the center to its appropriate height and width, centered on the canvas.
$('#ebay-pic').animate({
    width: 0,
    height: 0,
    marginTop: $('#ebay-pic').parent().height() / 2,
    opacity: 0
}, 100, function() {
    // Animation complete.
	$('#ebay-pic').parent().html("<%= escape_javascript(render(:partial => 'ebay_pic')) %>");
	var width = $('#ebay-pic').width();
	var height = $('#ebay-pic').height();
	var marginTop = $('#ebay-pic').parent().height() / 2 - height / 2;
	$('#ebay-pic').css('marginTop', $('#ebay-pic').parent().height() / 2);
	$('#ebay-pic').css('width', 0);
	$('#ebay-pic').css('height', 0);
	$('#ebay-pic').css('opacity', 0);
	$('#ebay-pic').animate({
    	width: width,
    	height: height,
    	marginTop: marginTop,
    	opacity: 100
	}, 100, function() {
	});
});

app/views/auctions/import.html.erb
<% if @auctions != [] %>

  <%= form_for @auctions, :url => { :action => "create_multiple" }, :method => :post do |f| %>
    <table class="table table-striped">
      <thead>
        <tr>
	      <th width="15%">Picture</th>
          <th width="55%">Title</th>
	      <th width="10%">Time Left</th>
	      <th width="15%">Price</th>
          <th width="5%">Import</th>
	      <th width="5%">Snipe options</th>
        </tr>
      </thead>

      <tbody>
        <% @auctions.each_with_index do |auction, index| %>
	      <tr <% if not auction.errors.empty? %> id="error_auction_<%= index %>"<% end %>>
            <td class="auction-link" onclick="window.open('<%= auction.item[:get_item_response][:item][:listing_details][:view_item_url] %>')"
            style="vertical-align: middle; text-align: center;" >
	          <%= image_tag auction.item[:get_item_response][:item][:picture_details][:picture_url] %></td>
	  	    <td class="auction-link" style="vertical-align: middle;"
	  	    onclick="window.open('<%= auction.item[:get_item_response][:item][:listing_details][:view_item_url] %>')">
	  		  <h3><%= auction.item[:get_item_response][:item][:title] %></h3>
	  		</td>
	  	    <td class="auction-link" style="vertical-align: middle;"
	  	    onclick="window.open('<%= auction.item[:get_item_response][:item][:listing_details][:view_item_url] %>')">
	  		  <%= get_time_remaining auction %>
	  		</td>
		    <td class="auction-link" style="vertical-align: middle;" onclick="window.open('<%= auction.item[:get_item_response][:item][:listing_details][:view_item_url] %>')">
		      <%= number_to_currency auction.item[:get_item_response][:item][:selling_status][:converted_current_price] %>
			</td>
            <%= fields_for 'auction[]', auction do |auction_fields| %>
		      <td style="vertical-align: middle; text-align: center;" style="text-align: center;">
		        <%= auction_fields.check_box :to_add %>
		        <%= auction_fields.hidden_field :item_id %>
			  </td>
		      <td>
			    Max bid: <%= auction_fields.text_field :max_bid %>
			    Lead time (0-3 seconds): <%= auction_fields.text_field :lead_time %>
			    Notification method: <%= auction_fields.select :user_notification, ["Do not notify", "Call", "Text Message"] %>
			  </td>
	        <% end %>
	        <% if  not auction.errors.empty? %>
	          <script>
	      	    $(document).ready(function() { 
	      	      $($("#error_auction_<%= index %> td")[2]).popover({trigger: 'manual', placement: "left", content: "<ul><% auction.errors.full_messages.each do |msg| %><li>  <%= escape_javascript(msg) %></li><% end %>", title: "<%= pluralize(auction.errors.count, "error") %> prohibited this auction from being saved:"});

	      		  $("#error_auction_<%= index %>").hover(function() {
	      		    if (! $("#error_auction_<%= index %>").attr("shown")) {
		      	     $($("#error_auction_<%= index %> td")[2]).popover('show'); 
		      	     $("#error_auction_<%= index %>").attr("shown", "true");
	      		    }
	      		  }, function() { 
	      	        // $($("#error_auction_<%= index %> td")[2]).popover('hide');
	      		  });
	      	    });
	      	  </script>
	        <% end %>
	      </tr>

	    <% end %>
      </tbody>
    </table>
    <br/>
    <button type="submit" class="btn btn-primary pull-right">
      Add Checked Auctions
    </button>
  <% end %>

<% else %>
  <div class="alert alert-error">
	<strong>Sorry!</strong> No auctions were found in your eBay account's WatchList that have not already been added.
  </div>
<% end %>

app/views/auctions/index.html.erb
<legend>My Auctions</legend>
<br/>

<div id="auction_index">
  <%= render :partial => "auction_index" %>
</div>

app/views/auctions/index.js.erb
$('#auction_index').html("<%= escape_javascript(render(:partial => 'auction_index')) %>");

app/views/auctions/remove_multiple.js.erb
<% @auctions.each do |auction| %>
  $('#auction-' + <%= auction.id %>).fadeOut(250)
<% end %>
$('body').animate({scrollTop:0}, 'fast');

app/views/auctions/restore_multiple.js.erb
<% @auctions.each do |auction| %>
  $('#auction-' + <%= auction.id %>).fadeOut(250);
<% end %>
$('body').animate({scrollTop:0}, 'fast');