config/routes.rb
EbaySniper::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "users", :sessions => "sessions" }
  
  resources :search do
    member do
      post :new
    end
  end
  
  resources :auctions do
    collection do
      post :remove_multiple
      post :restore_multiple
      post :create_multiple
      get :import
    end
    member do
      post :restore
      get :update_info
    end
  end

  resources :users
  resources :home
  resources :notifications
  
  get "call_handler", :to => "notifications#receive"
  
  devise_scope :user do
    get "user_root", :to => "users#check_token"
    get "user/add_token", :to => "users#add_token"
    get "user/check_token", :to => "users#check_token"
    get "user/consent_failed", :to => "users#consent_failed"
  end

  root :to => "home#index"

  

end

app/models/user.rb
require 'devise/strategies/base'
require 'devise'

module Devise
  module Strategies
    # Remember the user through the remember token. This strategy is responsible
    # to verify whether there is a cookie with the remember token, and to
    # recreate the user from this cookie if it exists. Must be called *before*
    # authenticatable.
    class EbayAuthenticatable < Authenticatable

      def valid?
        if params and params.is_a?(Hash) and params[:user] and params[:user].is_a?(Hash) and params[:user][:email] and not (params[:user][:email].to_s =~ /@/)
          params_authenticatable? && valid_params_request? &&
            valid_params? && with_authentication_hash(:params_auth, params_auth_hash)
          return true
        else
          return false
        end
      end

      # To authenticate a user we deserialize the cookie and attempt finding
      # the record in the database. If the attempt fails, we pass to another
      # strategy handle the authentication.
      def authenticate!
        resource = mapping.to.where(:username => authentication_hash[:email]).first if authentication_hash
        resource ||= mapping.to.new if resource.nil?

        username = authenticate_against_ebay(authentication_hash[:email], password)

        if username
          resource.username = username
          resource.password = password
          resource.password_confirmation = password
          resource.save if resource.changed?
        end

        return fail(:invalid) unless username and resource

        if validate(resource) { not resource.nil? }
          success!(resource)
        end
      end

      def authenticate_against_ebay(username, password)
        m = Mechanize.new
        lp = m.get "https://signin.sandbox.ebay.com/ws/eBayISAPI.dll?SignIn"
        f = lp.form_with(:name => "SignInForm")
        f.field_with(:name => "userid").value = username
        f.field_with(:name => "pass").value = password
        np = f.submit

        if np.body =~ /password is incorrect/
          return false
        end

        myebay = m.get "http://my.sandbox.ebay.com/ws/eBayISAPI.dll?MyeBay"
        return myebay.search("[class='mbg-nw']").text
      end

      private

      def decorate(resource)
        super
        # resource.extend_remember_period = mapping.to.extend_remember_period if resource.respond_to?(:extend_remember_period=)
      end

    end
  end
end

module Devise
  module Models
    module EbayAuthenticatable
      def self.included(base)
        base.extend ClassMethods
      end

      module ClassMethods
      end
    end


    module Validatable
      # All validations used by this module.
      # VALIDATIONS = [ :validates_presence_of, :validates_uniqueness_of, :validates_format_of,
      # :validates_confirmation_of, :validates_length_of ].freeze

      def self.included(base)
        base.extend ClassMethods
        assert_validations_api!(base)

        base.class_eval do
          validates_presence_of   :email, :if => :email_required?
          validates_uniqueness_of :email, :case_sensitive => (case_insensitive_keys != false), :allow_blank => false, :if => :email_changed?
          validates_format_of     :email, :with => email_regexp, :allow_blank => false, :if => :email_changed?

          validates_presence_of     :password, :if => :password_required?
          validates_confirmation_of :password, :if => :password_required?
          validates_length_of       :password, :within => password_length, :allow_blank => true
        end
      end
    end
  end
end

Warden::Strategies.add(:ebay_authenticatable, Devise::Strategies::EbayAuthenticatable)
Devise.add_module(:ebay_authenticatable,
                  :strategy => true,
                  :model => "app/models/user.rb")

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable, :ebay_authenticatable

  has_many :auctions, dependent: :destroy
  validates :phone_number, :allow_blank => true, :length => { :is => 12 }, :format => { :with => /\A[+]\d+\z/,
                                                                                        :message => "should include your country code. A US number would be +1##########." }
  validates_uniqueness_of :phone_number, :allow_blank => true, :message => "is already tied to an account."
  before_create do
    self.auth_token ||= SecureRandom.hex(23)
  end

  def self.currently_online
    online_ids = $redis.keys("ebay_sniper:online_users:*").map { |v| v.gsub("ebay_sniper:online_users:", "") }
    User.where(:id => online_ids)
  end

  def consent_failed?
    if self.auth_token_exp < Time.now
      return true
    else
      return false
    end
  end

  def online?
    if self.id
      return $redis.get("ebay_sniper:online_users:#{self.id}") == "1"
    end
    return false
  end

  def email_required?
    return false
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  
  def add_token
    # Using rescue to make sure user doesn't stumble upon this without using the correct parameters.
    begin
      # Use the session_id to fetch the user's auth token and username and save those values
      @user = User.find(params[:user_id])
      @user.username = params[:username]
      EbayAction.new(@user).fetch_token
    rescue
      # If the user_id doesn't exist, do nothing
    end
    redirect_to root_path
  end
  
  def consent_failed
    begin
      @user = User.find(params[:user_id])
      @consent_url = EbayAction.new(@user).get_session_id
    rescue
      redirect_to new_user_session_path
    end
  end
  
  def check_token
    # Not sure how to override devise new session method to pass params, so assigning user to current_user. Using rescue as authenticate_user!
    begin
      @user = current_user
      if @user.auth_token == nil || @user.auth_token_exp < Time.now
        redirect_to user_consent_failed_path + "?user_id=#{@user.id}"
      else
        redirect_to root_path
      end
    rescue
      redirect_to new_user_session_path
    end
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit_modal.html.erb
  <% if current_user %>
    <div id="edit_account" class="modal hide fade in">
      <div>
        <a class="close" data-dismiss="modal">×</a>
      </div>
      <% user = current_user %>
        <%= form_for user, { :url => users_path, :remote => true } do |f| %>
        <% if not user.errors.any? %>
          <br/>
        <% end %>
        <div class="modal-body">
          <legend>Edit Account</legend>
          <br/>
          <div class="control-group">
            <label class="control-label" for="item_id">Email</label>
               <div class="controls">
              <%= f.text_field :email %>
            </div>
          </div>
          <br/>
          <div class="control-group">
            <label class="control-label" for="item_id">Password (leave blank if you don't want to change it)</label>
            <div class="controls">
              <%= f.password_field :password, :autocomplete => "off" %>
            </div>
          </div>
          <br/>
          <div class="control-group">
            <label class="control-label" for="item_id">Password confirmation</label>
            <div class="controls">
              <%= f.password_field :password_confirmation %>
            </div>
          </div>
          <br/>
          <div class="control-group">
            <label class="control-label" for="item_id"><b>Current password</b> (needed to confirm changes)</label>
               <div class="controls">
              <%= f.password_field :current_password %>
            </div>
          </div>
          <br/>
          <div class="control-group">
            <label class="control-label" for="item_id">Phone number</label>
            <div class="controls">
               <%= f.text_field :phone_number %>
            </div>
          </div>
          <br/>
        </div>
        <div class="modal-footer" style="text-align: left;">
          <button type="submit" class="btn btn-primary">Save Changes</button> |
          <%= link_to "Change eBay accounts", user_consent_failed_path + "?user_id=#{user.id}", :class => "btn btn-inverse" %> |
          <%= link_to "Delete account", registration_path(user), :data => { :confirm => "Are you sure you want to delete your Levion eBay Sniper account?" },
              :method => :delete, :class => "btn btn-danger" %> |
          <a href="#" class="btn" data-dismiss="modal">Close</a>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/users/_errors.html.erb
<% if user.errors.empty? %>
  <div id="user-update-result" class="alert alert-success">
    <button type="button" class="close" data-dismiss="alert">×</button>
    <strong>Well done!</strong> Your account was successfully updated.
  </div>
<% else %>
  <div id="user-update-result" class="alert alert-error alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button>

    <h4><%= pluralize(user.errors.count, "error") %> prohibited this auction from being saved:</h4>
    <ul style="padding-top: 10px">
      <% user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/consent_failed.html.erb
<legend>eBay Account Linking</legend>

<br/>

Either your eBay account's authorization token has expired, or you have failed to consent to allow our application to access your eBay account. It is necessary for you to allow this if you wish to use this application. Please click the link below, sign in to your eBay account and click the "I agree" button.

<br/><br/><br/>


<%= link_to "Authenticate account", @consent_url, :class => "btn btn-primary" %>

app/views/users/edit.html.erb
<legend>Edit Account</legend>
<br/>
<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :method => :put }) do |f| %>
  <%= devise_error_messages! %>

  <fieldset>
  <div class="control-group">
    <label class="control-label" for="item_id">Email</label>
    <div class="controls">
	  <%= f.text_field :email %>
    </div>
  </div>
  <br/>
  <div class="control-group">
    <label class="control-label" for="item_id">Password (leave blank if you don't want to change it)</label>
    <div class="controls">
 	  <%= f.password_field :password, :autocomplete => "off" %>
    </div>
  </div>
  <br/>
  <div class="control-group">
    <label class="control-label" for="item_id">Password confirmation</label>
    <div class="controls">
 	  <%= f.password_field :password_confirmation %>
    </div>
  </div>
  <br/>
  <div class="control-group">
    <label class="control-label" for="item_id"><b>Current password</b> (needed to confirm changes)</label>
    <div class="controls">
 	  <%= f.password_field :current_password %>
    </div>
  </div>
  <br/>
  <div class="control-group">
    <label class="control-label" for="item_id">Phone number</label>
    <div class="controls">
 	  <%= f.text_field :phone_number %>
    </div>
  </div>
</fieldset>
  <br/>
  <button type="submit" class="btn btn-primary">Save changes</button> |
  <%= link_to "Change eBay accounts", user_consent_failed_path + "?user_id=#{@user.id}", :class => "btn btn-inverse" %> |
  <%= link_to "Delete account", registration_path(resource_name), :data => { :confirm => "Are you sure?" }, :method => :delete,
 	  :class => "btn btn-danger" %>
<% end %>

app/views/users/new.html.erb
<legend>Sign up</legend>
<br/>

<%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <fieldset>
  <div class="control-group">
    <label class="control-label" for="item_id">Email</label>
    <div class="controls">
	  <%= f.text_field :email %>
    </div>
  </div>
  <br/>
  <div class="control-group">
    <label class="control-label" for="item_id">Password (leave blank if you don't want to change it)</label>
    <div class="controls">
 	  <%= f.password_field :password %>
    </div>
  </div>
  <br/>
  <div class="control-group">
    <label class="control-label" for="item_id">Password confirmation</label>
    <div class="controls">
 	  <%= f.password_field :password_confirmation %>
    </div>
  </div>
  <br/>
  <div class="control-group">
    <label class="control-label" for="item_id">Phone number (to be contacted regarding critical auction updates)</label>
    <div class="controls">
 	  <%= f.password_field :phone_number %>
    </div>
  </div>

  <br/>
  <button type="submit" class="btn btn-primary">Sign up</button>
<% end %>

app/views/users/update.js.erb
<% if @user.errors.empty? %>
  $('#edit_account').modal('hide');
  $('#edit_account').detach();
  $('footer').before('<%= escape_javascript(render('users/edit_modal', :user => @user)); %>');
  $('#user-update-result').detach();
  $('#main legend:first').before('<%= escape_javascript(render('users/errors', :user => @user)) %>');
  $('html, body').animate({scrollTop:0}, 'fast')
<% else %>
  $('#user-update-result').detach();
  $('#edit_account .modal-body legend').before('<%= escape_javascript(render('users/errors', :user => @user)) %>');
  $('#edit_account, .modal-body').animate({scrollTop:0}, 'fast');
  $('#user-update-result').effect("highlight", {}, 1000);
<% end %>