config/routes.rb
EbaySniper::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "users", :sessions => "sessions" }
  
  resources :search do
    member do
      post :new
    end
  end
  
  resources :auctions do
    collection do
      post :remove_multiple
      post :restore_multiple
      post :create_multiple
      get :import
    end
    member do
      post :restore
      get :update_info
    end
  end

  resources :users
  resources :home
  resources :notifications
  
  get "call_handler", :to => "notifications#receive"
  
  devise_scope :user do
    get "user_root", :to => "users#check_token"
    get "user/add_token", :to => "users#add_token"
    get "user/check_token", :to => "users#check_token"
    get "user/consent_failed", :to => "users#consent_failed"
  end

  root :to => "home#index"

  

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
    <a class="close" data-dismiss="alert">&#215;</a>
    <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
	<div class="container">
	  <ul class="nav">
		<li class="active">
		  <a class="brand" href="http://www.levion.com" target="_blank"><%= image_tag "logo.png", :size => "135x33" %></a>
		</li>
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "My Auctions", auctions_path %></li>
		<% if user_signed_in? %>
		  <li><a data-toggle="modal" href="#new_auction">Add Auction</a></li>
		<% else %>
		  <li><%= link_to('Add Auction', new_user_session_path) %></li>
		<% end %>
		<li>
		  <%= form_tag(search_index_path, { :method => :get, :class => "navbar-search pull-left" }) do |f| %>
			<%= text_field_tag :search, nil, { :class => "search-query", :placeholder => "Search your auctions" } %>
		  <% end %>
		</li>
	  </ul>
	  <ul class="nav pull-right">
		
		<% if user_signed_in? %>
		  <li class="pull-right"><%= link_to('Logout', destroy_user_session_path, :method=>'delete') %></li>
  		<% else %>
	      <li class="pull-right"><%= link_to('Login', new_user_session_path) %></li>
	  	<% end %>
		<% if user_signed_in? %>
		  <li class="pull-right"><a data-toggle="modal" href="#edit_account">Edit Account</a></li>
  		<% else %>
    	  <li class="pull-right"><%= link_to('Sign up', new_user_registration_path) %></li>
  		<% end %>

	  </ul>
	</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Levion eBay Sniper" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
          <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>

          <%= render 'auctions/new_modal' %>
		  
          <%= render 'users/edit_modal' %>

          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->

  </body>
</html>